### ISSUE TITLE
Implement serverless-golang as a plugin

### ISSUE THREAD

**Issue by alias1** [yunspace/serverless-golang#23]
The current setup/example are nice, but I wonder if serverless-golang could be implemented as a plugin as per:
* https://serverless.com/framework/docs/providers/aws/guide/plugins/

It would make the whole process seem a lot more 'integrated'.

**Comment by yunspace** [comment]
@alias1 thanks for the suggestion and definitely agree. 

Back in April @cristim did propose to add this to the serverless `create templates`: https://github.com/serverless/serverless/issues/2712 The maintainers expressed they wish to keep the `create templates` to only officially supported languages, which is understandable. We did get added into the official examples page which is pretty awesome.

Whilst I haven't looked into make this into a "project creation" plugin as you have suggested. I suspect it might not be as straight forward. Since The core design of this library is very docker centric, relying on immutable versions of AWS linux + Python + Go + Node + SLS. Where as the default SLS plugins are very much node centric, dependencies are fully mutable and you can have any version of node with any version of SLS installed.

After NYC serverlessconf in October I'll have some free time and may re-visit the possibility. Mean while please feel free to experiment and let me know how you go! 👍

**Comment by cristim** [comment]
AWS Lambda will eventually support Go natively, serverless will need to add native support for it and then serverless-golang and the underlying eawsy Lambda shim will be rendered obsolete.

In the meantime I think the current serverless project skeleton approach is good enough to build things in Go, and it will be relatively easy to migrate to the native implementation once that's available.

**Comment by yunspace** [comment]
Valid points indeed. I will close this for now.
